[project]
name = "zbitvector"
description = "A well-typed library for symbolic bitvectors"
readme = "README.md"

# zbitvector is MIT-licensed. However, the binary wheel packages Bitwuzla and
# its dependencies, which include GMP (LGPLv3) and SymFPU (GPLv3).
license = { text = "GNU General Public License v3" }

dynamic = ["version"]

requires-python = ">= 3.8"
dependencies = ["typing-extensions >= 4.0"]

[build-system]
requires = ["cython", "setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-all = ["make ci"]
test-command = 'python3 -c "import zbitvector; Uint8 = type(\"Uint8\", (zbitvector.Uint,), {\"width\": 8}); print(Uint8(1) + Uint8(2))"'

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[tool.setuptools]
packages = ["zbitvector", "zbitvector.pybitwuzla"]

[tool.setuptools_scm]
