[project]
name = "zbitvector"
version = "1.0b1"
description = "A well-typed library for symbolic bitvectors"
readme = "README.md"

# zbitvector is MIT-licensed. However, the binary wheel packages Bitwuzla and
# its dependencies, which include GMP (LGPLv3) and SymFPU (GPLv3).
license = { text = "GNU General Public License v3" }

requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["zbitvector"]

[tool.cibuildwheel.linux]
# For now, build images for Linux on 64-bit Intel. We use manylinux_2_28, the
# most recent supported image, which is compatible with distros released in
# ~2018+ (https://github.com/mayeut/pep600_compliance).
build = ["*_x86_64"]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-pypy_x86_64-image = "manylinux_2_28"
before-all = ["make ci"]

[tool.cibuildwheel.macos]
before-all = ["sudo make ci"]
