[project]
name = "zbitvector"
description = "A well-typed library for symbolic bitvectors"
readme = "README.md"

# zbitvector is MIT-licensed. However, the binary wheel packages Bitwuzla and
# its dependencies, which include GMP (LGPLv3) and SymFPU (GPLv3).
license = { text = "GNU General Public License v3" }

dynamic = ["version"]

requires-python = ">= 3.8"
dependencies = ["typing-extensions >= 4.0"]

[build-system]
requires = ["setuptools", "setuptools_scm[toml]", "cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["zbitvector", "zbitvector.pybitwuzla"]

[tool.setuptools_scm]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
before-all = ["sudo make ci"]

[tool.cibuildwheel.linux]
archs = ["auto64"]
before-all = ["make ci"]

[tool.pytest.ini_options]
addopts = "--doctest-modules"
