name: documentation
on: [push, pull_request, workflow_dispatch]
concurrency:
  group: documentation
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # We need to build and install zbitvector so that sphinx-autodoc can
      # import it. GMP blackholes GitHub Actions, so we install it from the
      # Ubuntu package instead.
      - run: |
          pip install build sphinx
          sudo apt install -y libgmp-dev
          sudo make /usr/local/include/bitwuzla/bitwuzla.h -o /usr/local/include/gmp.h
          sudo ldconfig
          make build
          pip install dist/zbitvector-*.whl
      - run: make -C docs html
        env:
          O: -W # fail on warning
          SPHINX_NO_LOCAL: 1
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v2
        id: deploy-pages
