name: typecheck
on: [workflow_dispatch]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh release create v1.2.0 --generate-notes --verify-tag
