name: release
on: [workflow_dispatch]

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh release create v1.2.0 --draft --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
