name: release
on: [workflow_dispatch]
concurrency:
  group: release
  cancel-in-progress: false

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: .github/workflows/release.sh
        env:
          GH_TOKEN: ${{ github.token }}
