name: Build and deploy documentation
on: [push, workflow_dispatch]
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install sphinx
      - run: make -C docs html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v2
        id: deploy-pages
